local wezterm = require('wezterm')

return {
    enable_wayland = true,
    check_for_updates = false,
    front_end = 'OpenGL',
    window_background_opacity = 0.7,
    window_close_confirmation = "NeverPrompt",
    term = 'wezterm',
    color_scheme = "Catppuccin Mocha",
    colors = { background = '#000000', },
    bold_brightens_ansi_colors = true,
    font = wezterm.font_with_fallback {
        "JetBrains Mono",
        'Symbols Nerd Font',
    },
    font_size = 10,
    line_height = 1.5,
    allow_square_glyphs_to_overflow_width = "Never",
    custom_block_glyphs = true,
    animation_fps = 120,
    enable_scroll_bar = false,
    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    },
    hide_tab_bar_if_only_one_tab = true,
    use_fancy_tab_bar = false,
    show_new_tab_button_in_tab_bar = false,
    underline_position = "200%",
    -- underline_thickness = 2,
    detect_password_input = false,
}
