alias icat='kitty +kitten icat'
alias ls='exa --icons -l'
alias f='fzf'
alias v='nvim'
alias n='nnn -eH'
alias N='sudo -E nnn -deH'
alias tree='erdtree'
alias rustscan='docker run -it --rm --name rustscan rustscan/rustscan:latest'
alias svn="svn --config-dir $XDG_CONFIG_HOME/subversion"
