#!/usr/bin/bash

export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache
config=$HOME/.config/hypr
scripts=$config/scripts

swww init
dunst &
waybar &

eval $(/usr/bin/gnome-keyring-daemon --start)
export $(dbus-launch)

casio &
docker restart libreddit &
