#!/usr/bin/bash

config=$HOME/.config/hypr
scripts=$config/scripts

swww init
dunst &
waybar &
casio &
docker restart libreddit &

eval $(/usr/bin/gnome-keyring-daemon --start)
export $(dbus-launch)

