#!/usr/bin/bash

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
swww-daemon &
waybar &
hypridle &
fcitx5 &

eval $(/usr/bin/gnome-keyring-daemon --start)
export $(dbus-launch)
ln -s $XDG_RUNTIME_DIR/hypr /tmp/hypr
