#!/usr/bin/bash

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
swww init &
dunst &
waybar &
ydotoold &

swayidle -w timeout 300 'lock' timeout 360 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep 'lock' &

eval $(/usr/bin/gnome-keyring-daemon --start)
export $(dbus-launch)
