theme = "catppuccin"

[editor]
color-modes = true
true-color = true
bufferline = "multiple"
auto-save = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "file-type","file-encoding", "file-line-ending", "position"]
separator = "\u2502"

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
