services:
  owncloud:
    image: owncloud/server:latest    # 10.13.2-arm64v8
    container_name: owncloud
    restart: always
    ports:
      - 9003:8080
    depends_on:
      - db
      - redis
    environment:
      # - OWNCLOUD_DOMAIN=tudominio.com  # IP:8080 # Nombre dominio válido    
      - OWNCLOUD_TRUSTED_DOMAINS=172.26.161.127  # IP # Nombre dominio válido 
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - ~/data/owncloud/data:/mnt/data

  db:
    image: mariadb:latest
    container_name: owncloud-db
    restart: always
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]      
    volumes:
      - ~/data/owncloud/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: owncloud-redis
    restart: always
    command: ["--databases", "1"]
    volumes:
      - ~/data/owncloud/redis:/data
   
